import { useCallback } from "react";
import Property1LabelOutlineDefau from "./Property1LabelOutlineDefau";
import { useNavigate } from "react-router-dom";
import "./Container1.css";

const Container1 = () => {
  const navigate = useNavigate();

  const onFrameContainer1Click = useCallback(() => {
    navigate("/account-setup");
  }, [navigate]);

  const onAlreadyHaveAnClick = useCallback(() => {
    navigate("/sign-in");
  }, [navigate]);

  return (
    <div className="frame-parent35">
      <div className="text-field-parent">
        <Property1LabelOutlineDefau
          plus="/plus.svg"
          label="Full Name*"
          plus1="/plus.svg"
          email="John Doe"
          plus2="/plus.svg"
          helperText="Helper text"
          lineDiv={false}
          windowCloseIcon={false}
          leftHelperText={false}
          showHelperText
          property1LabelOutlineDefaWidth="unset"
          property1LabelOutlineDefaHeight="unset"
          plusIconWidth="16px"
          plusIconHeight="16px"
          labelFontSize="12px"
          textFieldWidth="266px"
          textFieldBorderRadius="0px 4px 4px 0px"
          textFieldBorder="1px solid var(--grey-500)"
          textFieldHeight="42px"
          textFieldPadding="var(--padding-xs) var(--padding-4xs)"
          textFieldGap="197px"
          textFieldAlignSelf="unset"
          textFieldBackgroundColor="unset"
          textFieldFlex="unset"
          plusIconWidth1="16px"
          plusIconHeight1="16px"
          emailFontSize="14px"
          emailColor="rgba(97, 97, 97, 0.5)"
          lineDivBorderRight="1px solid var(--color-black)"
          lineDivHeight="18px"
          lineDivWidth="1px"
          lineDivPosition="relative"
          lineDivMargin="unset"
          windowCloseIconWidth="16px"
          windowCloseIconHeight="16px"
          windowCloseIconPosition="relative"
          windowCloseIconOverflow="hidden"
          leftHelperTextFlexDirection="row"
          leftHelperTextGap="4px"
          leftHelperTextMargin="unset"
          plusIconWidth2="16px"
          plusIconHeight2="16px"
          plusIconOverflow="hidden"
          plusIconBorderRight="unset"
          helperTextFontSize="12px"
          helperTextFontWeight="900"
          helperTextLineHeight="140%"
          helperTextFontFamily="Poppins"
          helperTextColor="#000"
          helperTextTextAlign="left"
          helperTextWidth="unset"
          helperTextHeight="unset"
          helperTextOverflow="unset"
        />
        <Property1LabelOutlineDefau
          plus="/plus.svg"
          label="Username*"
          plus1="/plus.svg"
          email="johndoe"
          plus2="/plus.svg"
          helperText="Helper text"
          lineDiv={false}
          windowCloseIcon={false}
          leftHelperText={false}
          showHelperText
          property1LabelOutlineDefaWidth="unset"
          property1LabelOutlineDefaHeight="unset"
          plusIconWidth="16px"
          plusIconHeight="16px"
          labelFontSize="12px"
          textFieldWidth="266px"
          textFieldBorderRadius="0px 4px 4px 0px"
          textFieldBorder="1px solid var(--grey-500)"
          textFieldHeight="42px"
          textFieldPadding="var(--padding-xs) var(--padding-4xs)"
          textFieldGap="197px"
          textFieldAlignSelf="unset"
          textFieldBackgroundColor="unset"
          textFieldFlex="unset"
          plusIconWidth1="16px"
          plusIconHeight1="16px"
          emailFontSize="14px"
          emailColor="rgba(97, 97, 97, 0.5)"
          lineDivBorderRight="1px solid var(--color-black)"
          lineDivHeight="18px"
          lineDivWidth="1px"
          lineDivPosition="relative"
          lineDivMargin="unset"
          windowCloseIconWidth="16px"
          windowCloseIconHeight="16px"
          windowCloseIconPosition="relative"
          windowCloseIconOverflow="hidden"
          leftHelperTextFlexDirection="row"
          leftHelperTextGap="4px"
          leftHelperTextMargin="unset"
          plusIconWidth2="16px"
          plusIconHeight2="16px"
          plusIconOverflow="hidden"
          plusIconBorderRight="unset"
          helperTextFontSize="12px"
          helperTextFontWeight="900"
          helperTextLineHeight="140%"
          helperTextFontFamily="Poppins"
          helperTextColor="#000"
          helperTextTextAlign="left"
          helperTextWidth="unset"
          helperTextHeight="unset"
          helperTextOverflow="unset"
        />
        <Property1LabelOutlineDefau
          plus="/plus.svg"
          label="Phone Number*"
          plus1="/plus.svg"
          email="+254 xx xxx xxx"
          plus2="/plus.svg"
          helperText="Helper text"
          lineDiv={false}
          windowCloseIcon={false}
          leftHelperText={false}
          showHelperText
          property1LabelOutlineDefaWidth="unset"
          property1LabelOutlineDefaHeight="unset"
          plusIconWidth="16px"
          plusIconHeight="16px"
          labelFontSize="12px"
          textFieldWidth="266px"
          textFieldBorderRadius="0px 4px 4px 0px"
          textFieldBorder="1px solid var(--grey-500)"
          textFieldHeight="42px"
          textFieldPadding="var(--padding-xs) var(--padding-4xs)"
          textFieldGap="197px"
          textFieldAlignSelf="unset"
          textFieldBackgroundColor="unset"
          textFieldFlex="unset"
          plusIconWidth1="16px"
          plusIconHeight1="16px"
          emailFontSize="14px"
          emailColor="rgba(97, 97, 97, 0.5)"
          lineDivBorderRight="1px solid var(--color-black)"
          lineDivHeight="18px"
          lineDivWidth="1px"
          lineDivPosition="relative"
          lineDivMargin="unset"
          windowCloseIconWidth="16px"
          windowCloseIconHeight="16px"
          windowCloseIconPosition="relative"
          windowCloseIconOverflow="hidden"
          leftHelperTextFlexDirection="row"
          leftHelperTextGap="4px"
          leftHelperTextMargin="unset"
          plusIconWidth2="16px"
          plusIconHeight2="16px"
          plusIconOverflow="hidden"
          plusIconBorderRight="unset"
          helperTextFontSize="12px"
          helperTextFontWeight="900"
          helperTextLineHeight="140%"
          helperTextFontFamily="Poppins"
          helperTextColor="#000"
          helperTextTextAlign="left"
          helperTextWidth="unset"
          helperTextHeight="unset"
          helperTextOverflow="unset"
        />
        <Property1LabelOutlineDefau
          plus="/plus.svg"
          label="Email*"
          plus1="/plus.svg"
          email="example@domain.com"
          plus2="/plus.svg"
          helperText="Helper text"
          lineDiv={false}
          windowCloseIcon={false}
          leftHelperText={false}
          showHelperText
          property1LabelOutlineDefaWidth="unset"
          property1LabelOutlineDefaHeight="unset"
          plusIconWidth="16px"
          plusIconHeight="16px"
          labelFontSize="12px"
          textFieldWidth="266px"
          textFieldBorderRadius="0px 4px 4px 0px"
          textFieldBorder="1px solid var(--grey-500)"
          textFieldHeight="42px"
          textFieldPadding="var(--padding-xs) var(--padding-4xs)"
          textFieldGap="197px"
          textFieldAlignSelf="unset"
          textFieldBackgroundColor="unset"
          textFieldFlex="unset"
          plusIconWidth1="16px"
          plusIconHeight1="16px"
          emailFontSize="14px"
          emailColor="rgba(97, 97, 97, 0.5)"
          lineDivBorderRight="1px solid var(--color-black)"
          lineDivHeight="18px"
          lineDivWidth="1px"
          lineDivPosition="relative"
          lineDivMargin="unset"
          windowCloseIconWidth="16px"
          windowCloseIconHeight="16px"
          windowCloseIconPosition="relative"
          windowCloseIconOverflow="hidden"
          leftHelperTextFlexDirection="row"
          leftHelperTextGap="4px"
          leftHelperTextMargin="unset"
          plusIconWidth2="16px"
          plusIconHeight2="16px"
          plusIconOverflow="hidden"
          plusIconBorderRight="unset"
          helperTextFontSize="12px"
          helperTextFontWeight="900"
          helperTextLineHeight="140%"
          helperTextFontFamily="Poppins"
          helperTextColor="#000"
          helperTextTextAlign="left"
          helperTextWidth="unset"
          helperTextHeight="unset"
          helperTextOverflow="unset"
        />
        <Property1LabelOutlineDefau
          plus="/plus.svg"
          label="Password*"
          plus1="/plus.svg"
          email="******* "
          plus2="/plus.svg"
          helperText="Helper text"
          lineDiv={false}
          windowCloseIcon={false}
          leftHelperText={false}
          showHelperText
          property1LabelOutlineDefaWidth="unset"
          property1LabelOutlineDefaHeight="unset"
          plusIconWidth="16px"
          plusIconHeight="16px"
          labelFontSize="12px"
          textFieldWidth="266px"
          textFieldBorderRadius="0px 4px 4px 0px"
          textFieldBorder="1px solid var(--grey-500)"
          textFieldHeight="42px"
          textFieldPadding="var(--padding-xs) var(--padding-4xs)"
          textFieldGap="197px"
          textFieldAlignSelf="unset"
          textFieldBackgroundColor="unset"
          textFieldFlex="unset"
          plusIconWidth1="16px"
          plusIconHeight1="16px"
          emailFontSize="14px"
          emailColor="rgba(97, 97, 97, 0.5)"
          lineDivBorderRight="1px solid var(--color-black)"
          lineDivHeight="18px"
          lineDivWidth="1px"
          lineDivPosition="relative"
          lineDivMargin="unset"
          windowCloseIconWidth="16px"
          windowCloseIconHeight="16px"
          windowCloseIconPosition="relative"
          windowCloseIconOverflow="hidden"
          leftHelperTextFlexDirection="row"
          leftHelperTextGap="4px"
          leftHelperTextMargin="unset"
          plusIconWidth2="16px"
          plusIconHeight2="16px"
          plusIconOverflow="hidden"
          plusIconBorderRight="unset"
          helperTextFontSize="12px"
          helperTextFontWeight="900"
          helperTextLineHeight="140%"
          helperTextFontFamily="Poppins"
          helperTextColor="#000"
          helperTextTextAlign="left"
          helperTextWidth="unset"
          helperTextHeight="unset"
          helperTextOverflow="unset"
        />
        <Property1LabelOutlineDefau
          plus="/plus.svg"
          label="Confirm Password*"
          plus1="/plus.svg"
          email="******* "
          plus2="/plus.svg"
          helperText="This is required"
          lineDiv
          windowCloseIcon
          leftHelperText
          showHelperText
          property1LabelOutlineDefaWidth="unset"
          property1LabelOutlineDefaHeight="unset"
          plusIconWidth="16px"
          plusIconHeight="16px"
          labelFontSize="12px"
          textFieldWidth="266px"
          textFieldBorderRadius="0px 4px 4px 0px"
          textFieldBorder="1px solid var(--tertiary-stock-market-red)"
          textFieldHeight="42px"
          textFieldPadding="var(--padding-xs) var(--padding-4xs)"
          textFieldGap="197px"
          textFieldAlignSelf="unset"
          textFieldBackgroundColor="#fdfcfc"
          textFieldFlex="unset"
          plusIconWidth1="16px"
          plusIconHeight1="16px"
          emailFontSize="14px"
          emailColor="#010614"
          lineDivBorderRight="unset"
          lineDivHeight="17px"
          lineDivWidth="0px"
          lineDivPosition="relative"
          lineDivMargin="unset"
          windowCloseIconWidth="16px"
          windowCloseIconHeight="16px"
          windowCloseIconPosition="relative"
          windowCloseIconOverflow="hidden"
          leftHelperTextFlexDirection="row"
          leftHelperTextGap="4px"
          leftHelperTextMargin="unset"
          plusIconWidth2="16px"
          plusIconHeight2="16px"
          plusIconOverflow="hidden"
          plusIconBorderRight="unset"
          helperTextFontSize="12px"
          helperTextFontWeight="unset"
          helperTextLineHeight="140%"
          helperTextFontFamily="Poppins"
          helperTextColor="#000"
          helperTextTextAlign="left"
          helperTextWidth="unset"
          helperTextHeight="unset"
          helperTextOverflow="unset"
        />
      </div>
      <div className="logo-64">
        <b className="sal2">SAL.</b>
        <img className="logo-6-child1" alt="" src="/group-39796.svg" />
      </div>
      <div className="continue-wrapper" onClick={onFrameContainer1Click}>
        <div className="continue">Continue</div>
      </div>
      <div className="already-have-an" onClick={onAlreadyHaveAnClick}>
        Already have an account?
      </div>
    </div>
  );
};

export default Container1;
